# Generated by Django 3.1.5 on 2021-01-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210113_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='附件简历'),
        ),
    ]
